name: Release Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release gem to RubyGems.org
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write # Required for trusted publishing
      contents: write # Required for `rake release`
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      
      - name: Run tests
        run: bundle exec rake test
      
      - name: Run linter
        run: bundle exec rake standard
      
      - uses: rubygems/release-gem@v1